language: node_js

node_js:
  - "node"
  
install: 
  - yarn install

script:
  - yarn run test
  - yarn run build
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn run deploy; fi

branches:
  except:
  - gh-pages

env: 
  global:
    - GITHUB_REPO: "diogofcunha/react-data-grid-extensions"

cache:
  yarn: true